[INTERNAL] gdb, testsuite, python: Update error handling for Python 3.13.2.
Using the latest Python 3.13.2, few python related tests were failing
because errors are now shown a bit differently.  So, these tests are
updated accordingly.

With older Python:

'''
python print (gdb.parse_and_eval ('a_point_t').format_string (invalid=True))
Python Exception <class 'TypeError'>: 'invalid' is an invalid keyword argument for this function
Error occurred in Python: 'invalid' is an invalid keyword argument for this function
(gdb) PASS: gdb.python/py-format-string.exp: format_string: lang_c: test_all_common: test_invalid_args: a_point_t with option invalid=True

 &

-pycmd exp
&"Traceback (most recent call last):\n"
&"  File \"/gdb/gdb/testsuite/gdb.python/py-mi-cmd.py\", line 76, in invoke\n"
&"    raise gdb.GdbError()\n"
&"gdb.GdbError\n"
^error,msg="Error occurred in Python."
(gdb)
PASS: gdb.python/py-mi-cmd.exp: -pycmd exp
'''

Now with Python 3.13.2, we have

’’’
python print (gdb.parse_and_eval ('a_point_t').format_string (invalid=True))^M
Python Exception <class 'TypeError'>: this function got an unexpected keyword argument 'invalid'^M
Error occurred in Python: this function got an unexpected keyword argument 'invalid'^M
(gdb) FAIL: gdb.python/py-format-string.exp: format_string: lang_c: test_all_common: test_invalid_args: a_point_t with option invalid=True

&

-pycmd exp^M
&"Traceback (most recent call last):\n"
&"  File \"gdb/testsuite/gdb.python/py-mi-cmd.py\", line 76, in invoke\n    raise gdb.GdbError()\n"^
&"gdb.GdbError\n"^M
^error,msg="Error occurred in Python."
(gdb)
FAIL: gdb.python/py-mi-cmd.exp: -pycmd exp (unexpected output)
’’’

Signed-off-by: Abdul Basit Ijaz <abdul.b.ijaz@intel.com>