gdb, intelgt: reset of 'suppress-cli-notifications' in auto attach script
If the auto-attach fails with an error, the 'suppress-cli-notifications'
may not be properly reset.  This causes unexpected behavior if the user
decides not to quit the GDB session, e.g.:

...
Debugging of GPU offloaded code is not enabled.
Set 'ZET_ENABLE_PROGRAM_DEBUGGING=1' in host process environment.

ERROR: gdbserver-ze failed to start.  Intel GPU debugging is not possible.
Set the environment variable INTELGT_AUTO_ATTACH_DISABLE=1 for disabling
auto-attach.

A debugging session is active.

      Inferior 1 [process 990976] will be killed.

Quit anyway? (y or n) n

Continuing with GPU-debugging disabled.

Thread 1.1 "2_matrix_mul_mu" received signal SIGABRT, Aborted.
(gdb) frame 2
(gdb) frame 2
    ..
...

The frame command must be issued twice as CLI notifications are still
suppressed.  Fix this by properly resetting the setting on errors.