python, intelgt: Put hook breakpoint on correct event.
Auto attach script for the intelgt target sets the hook breakpoint when
libze_loader library load event is detected.  But on some OSes e.g.
RHEL, gnu_debugdata section makes GDB create an in-memory objfile and
setting breakpoint to this results in creation of the hook BP twice.

Without this change, following traces are shown when GPU kernel offload
section of code starts:

intelgt: received .gnu_debugdata for /lib64/libze_loader.so.1 loaded \
event. Setting up bp hook.
intelgt: received /lib64/libze_loader.so.1 loaded event. Setting up bp hook.
intelgt: received .gnu_debugdata for /lib64/libze_intel_gpu.so.1 loaded event.
intelgt: received /lib64/libze_intel_gpu.so.1 loaded event.

This causes Breakpoint number to be invalid while trying to delete this
hook breakpoint:

intelgt: gdbserver-ze started for process 2101730.
intelgt: calling init_gt_inferiors(self).
intelgt: calling remove_gt_inf_if_stored_for_removal(self).
intelgt: no inferior is stored for removal.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path to script>/intelgt_auto_attach.py", line 109, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<path to script>/intelgt_auto_attach.py", line 595, in init_gt_inferiors
    self.hook_bp.delete()
RuntimeError: Breakpoint -17 is invalid.
Error while executing Python code.
intelgt: calling remove_gt_inf_if_stored_for_removal(self).
intelgt: no inferior is stored for removal.

So, to handle the issue, ignore the first load event in case of
gnu_debugdata section.