fixup! gdb, threads: add 'thread filter all/thread-id-list' command.
Add namespace for 'get_stopped_threads' function to avoid name clashing
with same function defined in lib/sycl.exp:

  ERROR: tcl error sourcing /home/gta/Work/01_Source/applications.debuggers.gdb/gdb/testsuite/gdb.threads/simd-thread-filter.exp.
  ERROR: tcl error code TCL WRONGARGS
  ERROR: wrong # args: should be "get_stopped_threads match_text"
      while executing
  "get_stopped_threads "$srcfile" $kernel_line"
      ("uplevel" body line 94)
      invoked from within
  "uplevel 1 $body"
      invoked from within
  "with_test_prefix [sycl_get_device_prefix $device] {