fixup! gdb, gdbserver: Add Intel APX register support
APX pseudo registers are covered with dword_regnums. The register names
I removed in amd64_pseudo_register_name are for raw registers and the
condition for this branch is never fulfilled.
Added one assert since it's not obvious that tdep->r16_regnum cannot be
-1 at this specific code path.

When I rebase apx on upstream master I see
~~~
ERROR: in testcase /tmp/gdb.arch/amd64-apx-corefile.exp
ERROR:  absolute path used
ERROR:  tcl error code NONE
ERROR:  tcl error info:
absolute path used
    while executing
"error "absolute path used""
    (procedure "clean_restart" line 28)
    invoked from within
"clean_restart "${binfile}""
    (procedure "test_apx_corefiles" line 4)
    invoked from within
~~~

This probably comes from upstream master changes. Fix it also for this
version.

Further fix some nits.