testsuite: add guard in 'native-extended-gdbserver.exp' board
The 'native-extended-gdbserver.exp' board file overwrites 'gdb_start' to
also start gdbserver.  In case of errors (e.g. on timeouts or if GDB
fails to initialize), test execution should be aborted and gdbserver
should not be started.  An exemplary GDB initialization error can be
reproduced in 'gdb.python/py-startup-opt.exp' if GDB is built against a
custom Python version and the binaries are later moved.  GDB still works
if PYTHONHOME is set to the new location.  However, the test adds
'set python ignore-environment on' to '.gdbearlyinit' such that the Python
runtime fails to initialize:

  Could not find platform independent libraries <prefix>
  Could not find platform dependent libraries <exec_prefix>
  Python path configuration:
    PYTHONHOME = (not set)
    PYTHONPATH = (not set)
    program name = '<path-to-python-prefix>/bin/python'
    isolated = 0
    environment = 0
    user site = 1
    safe_path = 0
    import site = 1
    is in build tree = 0
    stdlib dir = '<path-to-python-prefix>/lib/python3.11'
    sys._base_executable = '<path-to-python-prefix>/bin/python'
    sys.base_prefix = '<path-to-python-prefix>'
    sys.base_exec_prefix = '<path-to-python-prefix>'
    sys.platlibdir = 'lib'
    sys.executable = '<path-to-python-prefix>/bin/python'
    sys.prefix = '<path-to-python-prefix>'
    sys.exec_prefix = '<path-to-python-prefix>'
    sys.path = [
      '<path-to-python-prefix>/lib/python311.zip',
      '<path-to-python-prefix>/lib/python3.11',
      '<path-to-python-prefix>/lib/python3.11/lib-dynload',
    ]
  Error occurred computing Python errormessage.
  Python not initialized
  ERROR: (eof) GDB never initialized.

This causes TCL errors in the subsequent spawn of gdbserver:

  builtin_spawn gdb/gdbserver/gdbserver --once --multi localhost:2347
  Listening on port 2347
  ERROR: : spawn id exp6 not open
      while executing
  "expect {
  -i exp6 -timeout 60
	      -re "A program is being debugged already.*ill it.*y or n. $" {
		  send_gdb "y\n"
		  exp_continue
	      }
	      -re "unk..."
      ("uplevel" body line 1)
      invoked from within
  "uplevel $body" NONE : spawn id exp6 not open

Protect against this error in by checking if GDB successfully started.